coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "ipie/legacy/**.py"
  - "ipie/legacy/**.pyx"
  - "test_*.py"