dist: xenial

language: python

cache:
  pip: true

python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
    - "3.9"

addons:
    apt:
        packages:
            - libmpich-dev
            - mpich

before_install:
    - pip install -r requirements.txt
    - pip install pyscf
    # testcode
    - git clone https://github.com/pauxy-qmc/pauxy_test_data.git
    - git clone git://github.com/jsspencer/testcode

install:
    - python setup.py build_ext --inplace

script:
    # - cd tests
    # - export PYTHONPATH=$PYTHONPATH:$HOME/pyqumc
    # - python -c "import sys; print (sys.path)"
    # - python -c "import pyqumc; import pyqumc.analysis"
    # - python -c "import pyqumc.qmc"
    # - $HOME/testcode/bin/testcode.py -vvv
    # - cd $HOME/pyqumc
    # - python -m pytest -v
    - pytest -v
    # Temporary hack until pauxy is pip-able
    - echo $PYTHONPATH
    - export PYTHONPATH=$HOME/pyqumc:$PYTHONPATH
    - cd pauxy_test_data
    - mpiexec --version
    # Longer parallel tests
    - python ../testcode/bin/testcode.py -v  -e ../bin/pauxy run --user-option=pauxy launch_parallel 'mpiexec -np tc.nprocs python -u'
    # Test examples
    - cd ..
    - ./tools/run_examples.sh

after_failure:
    - cat */*.err*