dist: xenial

language: python

python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
    - "3.9"

addons:
    apt:
        packages:
            - libmpich-dev
            - mpich

before_install:
    - pip install pandas matplotlib scipy numpy h5py mpi4py pyblock pyscf pytest Cython
    - cd
    # testcode
    - git clone git://github.com/jsspencer/testcode

install:
    - cd -
    - python setup.py install

script:
    - cd tests
    - export PYTHONPATH=$PYTHONPATH:$HOME/pyqumc
    - python -c "import sys; print (sys.path)"
    - python -c "import pyqumc; import pyqumc.analysis"
    - python -c "import pyqumc.qmc"
    - $HOME/testcode/bin/testcode.py -vvv
    - cd $HOME/pyqumc
    - python -m pytest -v

after_failure:
    - cat */*.err*