name: Continuous Integration

on: [pull_request]

jobs:
  pytest36:
    name: Pytest Ubuntu
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pyscf pytest
          git config --global user.name ${GITHUB_ACTOR}
      - name: Pytest check
        run: python -m pytest --actually-quiet
  pytest37:
    name: Pytest Ubuntu
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pyscf pytest
          git config --global user.name ${GITHUB_ACTOR}
      - name: Pytest check
        run: python -m pytest --actually-quiet
