name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        mpi:
          - openmpi
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyblock
        pip install pyscf
        pip install pytest-cov
    - name: Install package
      run: |
        # HACK FOR LEGACY CODE!
        export BUILD_LEGACY_IPIE=1; python -m pip install -e .
    - name: pylint
      run: |
        pip install pylint 
        pylint -s no --disable=R,C ipie/
    - name: format
      run: |
        pip install black
        black --check ipie
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-xdist
        python -m pytest -n 6 --dist loadfile --cov=./ipie
    - name: mpi test
      run: |
        mpiexec -n 2 python -m pytest ipie/legacy/walkers/tests/test_handler.py
        mpiexec -n 6 python -m pytest ipie/estimators/tests/test_generic_chunked.py
        mpiexec -n 6 python -m pytest ipie/propagation/tests/test_generic_chunked.py
    - name: Test Integration
      timeout-minutes: 10
      run: |
        pip install pytest-mpi
        mpirun -np 4 python -u -m pytest -sv --with-mpi ipie/qmc/tests/test_mpi_integration.py
        ./tools/run_examples.sh
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1

