name: Publish ipie
on:
  release:
    types: [published]
# allows to run on github directly (but prevents automatic releases)
#  workflow_dispatch:


jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build --sdist

      - name: Publish to PyPI
        # pypi-publish has issues with macos
        run: |
            pip install twine
            export TWINE_USERNAME=__token__
            export TWINE_PASSWORD="${{ secrets.PYPI_API_TOKEN }}"
            twine upload --verbose ${{ github.workspace }}/dist/*.tar.gz


  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp38-* cp39-* cp310-*
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: "*-musllinux*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

      - name: Publish to PyPI
        # pypi-publish has issues with macos
        run: |
            pip install twine
            export TWINE_USERNAME=__token__
            export TWINE_PASSWORD="${{ secrets.PYPI_API_TOKEN }}"
            twine upload --verbose ${{ github.workspace }}/wheelhouse/*.whl
